_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.12.3
        t:
            "1":
                - 1
                - 5
                - 11
                - 49
                - 53
                - 55
                - 75
            "2":
                - 1
                - 5
                - 11
                - 49
                - 53
                - 55
                - 75
            "3":
                - 2
                - 13
                - 16
                - 23
                - 55
            "4": 3.12.3
            "5": 0.19.11
            "6": 4.52.3
            "8":
                - 5
            "12": 0.19.11
            "13": linux-x86_64
max_input_tokens:
    value: 1024
top_k:
    value: 5
